-- ============================================================
-- Step 1: Create Database and Schemas
-- ============================================================

USE ROLE ACCOUNTADMIN;
ALTER ACCOUNT SET CORTEX_ENABLED_CROSS_REGION = 'AWS_US';

CREATE WAREHOUSE IF NOT EXISTS WYZE_COMP_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

CREATE DATABASE IF NOT EXISTS WYZE_COMP_ANALYSIS;
CREATE SCHEMA IF NOT EXISTS WYZE_COMP_ANALYSIS.RAW;
CREATE SCHEMA IF NOT EXISTS WYZE_COMP_ANALYSIS.FINAL;

SHOW SCHEMAS IN DATABASE WYZE_COMP_ANALYSIS;
