-- ============================================================
-- Step 9: Grant Permissions
-- ============================================================

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE WYZE_COMP_WH;

GRANT USAGE ON DATABASE WYZE_COMP_ANALYSIS TO ROLE PUBLIC;
GRANT USAGE ON SCHEMA WYZE_COMP_ANALYSIS.RAW TO ROLE PUBLIC;
GRANT USAGE ON SCHEMA WYZE_COMP_ANALYSIS.FINAL TO ROLE PUBLIC;

GRANT SELECT ON ALL TABLES IN SCHEMA WYZE_COMP_ANALYSIS.RAW TO ROLE PUBLIC;
GRANT SELECT ON ALL TABLES IN SCHEMA WYZE_COMP_ANALYSIS.FINAL TO ROLE PUBLIC;
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA WYZE_COMP_ANALYSIS.FINAL TO ROLE PUBLIC;

GRANT USAGE ON CORTEX SEARCH SERVICE WYZE_COMP_ANALYSIS.FINAL.PRODUCT_REVIEW_SEARCH TO ROLE PUBLIC;
GRANT SELECT ON SEMANTIC VIEW WYZE_COMP_ANALYSIS.FINAL.COMP_ANALYSIS_SEMANTIC_VIEW TO ROLE PUBLIC;
GRANT USAGE ON WAREHOUSE WYZE_COMP_WH TO ROLE PUBLIC;

GRANT USAGE ON DATABASE SNOWFLAKE_INTELLIGENCE TO ROLE PUBLIC;
GRANT USAGE ON SCHEMA SNOWFLAKE_INTELLIGENCE.AGENTS TO ROLE PUBLIC;
GRANT USAGE ON AGENT SNOWFLAKE_INTELLIGENCE.AGENTS.COMP_ANALYSIS_AGENT TO ROLE PUBLIC;
