-- ============================================================
-- Step 5a: Create SALES_ENRICHED Dynamic Table
-- ============================================================
-- Denormalizes sales with product, brand, subcategory, segment info

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE WYZE_COMP_WH;

CREATE OR REPLACE DYNAMIC TABLE WYZE_COMP_ANALYSIS.FINAL.SALES_ENRICHED
    TARGET_LAG = '1 day'
    WAREHOUSE = WYZE_COMP_WH
AS
SELECT
    s.SALE_ID,
    s.PRODUCT_ID,
    s.WEEK_ID,
    p.ASIN,
    p.PRODUCT_NAME,
    b.BRAND_NAME,
    b.IS_WYZE_COMPETITOR,
    sc.SUBCATEGORY_NAME,
    seg.SEGMENT_NAME,
    s.RETAIL_SALES,
    s.UNITS_SOLD,
    s.RETAIL_PRICE,
    s.ORGANIC_SALES,
    s.PAID_SALES,
    p.RATING,
    p.REVIEW_COUNT,
    p.CONTENT_SCORE,
    p.TITLE_SCORE,
    p.BULLET_SCORE,
    p.IMAGE_SCORE,
    p.VIDEO_SCORE,
    p.APLUS_SCORE,
    CASE
        WHEN s.UNITS_SOLD > 0 THEN ROUND(s.RETAIL_SALES / s.UNITS_SOLD, 2)
        ELSE 0
    END AS ASP,
    CASE
        WHEN s.RETAIL_SALES > 0 THEN ROUND(s.ORGANIC_SALES / s.RETAIL_SALES * 100, 1)
        ELSE 0
    END AS ORGANIC_SALES_PCT,
    CASE
        WHEN p.CONTENT_SCORE < 0.60 THEN 'Below Threshold'
        WHEN p.CONTENT_SCORE < 0.80 THEN 'Acceptable'
        ELSE 'Strong'
    END AS CONTENT_QUALITY_TIER,
    CASE
        WHEN p.RATING < 3.5 THEN 'Poor'
        WHEN p.RATING < 4.0 THEN 'Below Average'
        WHEN p.RATING < 4.5 THEN 'Good'
        ELSE 'Excellent'
    END AS RATING_TIER,
    CURRENT_TIMESTAMP() AS UPDATED_AT
FROM WYZE_COMP_ANALYSIS.RAW.ATLAS_SALES s
JOIN WYZE_COMP_ANALYSIS.RAW.PRODUCTS p ON s.PRODUCT_ID = p.PRODUCT_ID
JOIN WYZE_COMP_ANALYSIS.RAW.BRANDS b ON s.BRAND_ID = b.BRAND_ID
LEFT JOIN WYZE_COMP_ANALYSIS.RAW.SUBCATEGORIES sc ON p.SUBCATEGORY_ID = sc.SUBCATEGORY_ID
LEFT JOIN WYZE_COMP_ANALYSIS.RAW.SEGMENTS seg ON p.SEGMENT_ID = seg.SEGMENT_ID;

-- ============================================================
-- Verify
-- ============================================================

SELECT COUNT(*) AS total_rows FROM WYZE_COMP_ANALYSIS.FINAL.SALES_ENRICHED;
SELECT BRAND_NAME, COUNT(*) AS ROWS, ROUND(SUM(RETAIL_SALES), 0) AS TOTAL_SALES
FROM WYZE_COMP_ANALYSIS.FINAL.SALES_ENRICHED
GROUP BY BRAND_NAME ORDER BY TOTAL_SALES DESC LIMIT 5;
