-- ============================================================
-- Step 5b: Create PROMO_ENRICHED Dynamic Table
-- ============================================================
-- Denormalizes promotions with product and brand info

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE WYZE_COMP_WH;

CREATE OR REPLACE DYNAMIC TABLE WYZE_COMP_ANALYSIS.FINAL.PROMO_ENRICHED
    TARGET_LAG = '1 day'
    WAREHOUSE = WYZE_COMP_WH
AS
SELECT
    pr.PROMO_ID,
    pr.PRODUCT_ID,
    pr.WEEK_ID,
    p.PRODUCT_NAME,
    b.BRAND_NAME,
    b.IS_WYZE_COMPETITOR,
    sc.SUBCATEGORY_NAME,
    seg.SEGMENT_NAME,
    pr.PROMO_TYPE,
    pr.DISCOUNT_PCT,
    pr.PROMO_SALES,
    pr.PROMO_UNITS,
    pr.BASELINE_SALES,
    pr.BASELINE_UNITS,
    p.RETAIL_PRICE AS LIST_PRICE,
    CASE
        WHEN pr.BASELINE_SALES > 0
        THEN ROUND((pr.PROMO_SALES - pr.BASELINE_SALES) / pr.BASELINE_SALES * 100, 1)
        ELSE 0
    END AS SALES_LIFT_PCT,
    CASE
        WHEN pr.BASELINE_UNITS > 0
        THEN ROUND((pr.PROMO_UNITS - pr.BASELINE_UNITS) / pr.BASELINE_UNITS * 100, 1)
        ELSE 0
    END AS UNIT_LIFT_PCT,
    CASE
        WHEN pr.PROMO_UNITS > 0
        THEN ROUND(pr.PROMO_SALES / pr.PROMO_UNITS, 2)
        ELSE 0
    END AS PROMO_ASP,
    CASE
        WHEN pr.BASELINE_UNITS > 0
        THEN ROUND(pr.BASELINE_SALES / pr.BASELINE_UNITS, 2)
        ELSE 0
    END AS BASELINE_ASP,
    CASE
        WHEN pr.BASELINE_UNITS > 0 AND pr.PROMO_UNITS > 0
        THEN ROUND(
            (pr.PROMO_SALES / pr.PROMO_UNITS) - (pr.BASELINE_SALES / pr.BASELINE_UNITS), 2
        )
        ELSE 0
    END AS ASP_COMPRESSION,
    CURRENT_TIMESTAMP() AS UPDATED_AT
FROM WYZE_COMP_ANALYSIS.RAW.ATLAS_PROMOTIONS pr
JOIN WYZE_COMP_ANALYSIS.RAW.PRODUCTS p ON pr.PRODUCT_ID = p.PRODUCT_ID
JOIN WYZE_COMP_ANALYSIS.RAW.BRANDS b ON pr.BRAND_ID = b.BRAND_ID
LEFT JOIN WYZE_COMP_ANALYSIS.RAW.SUBCATEGORIES sc ON p.SUBCATEGORY_ID = sc.SUBCATEGORY_ID
LEFT JOIN WYZE_COMP_ANALYSIS.RAW.SEGMENTS seg ON p.SEGMENT_ID = seg.SEGMENT_ID;

SELECT COUNT(*) AS total_rows FROM WYZE_COMP_ANALYSIS.FINAL.PROMO_ENRICHED;
